apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-mysql
data:
    password: {{ .Values.mysql.password | b64enc }}
    user: {{ .Values.mysql.user | b64enc }}
    password2: {{ .Values.mysql.password2 | b64enc }}