apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.mysql.service.name }}
  labels:
    {{- template "mysql.labels" . | nindent 4 }}
spec:
  type: {{ .Values.mysql.service.type }}
  ports:
    - port: {{ .Values.mysql.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- template "mysql.selectorLabels" . | nindent 4 }}
