apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "crudappreact.fullname" . }}
  labels:
    {{- include "crudappreact.labels" . | nindent 4 }}
spec:
  {{- if not .Values.crudappreact.autoscaling.enabled }}
  replicas: {{ .Values.crudappreact.replicaCount }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "crudappreact.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.crudappreact.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "crudappreact.selectorLabels" . | nindent 8 }}
    spec:
      {{- with .Values.crudappreact.imagePullSecrets }}
      imagePullSecrets:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      serviceAccountName: {{ include "crudappreact.serviceAccountName" . }}
      securityContext:
        {{- toYaml .Values.crudappreact.podSecurityContext | nindent 8 }}
      containers:
        - name: {{ .Chart.Name }}
          securityContext:
            {{- toYaml .Values.crudappreact.securityContext | nindent 12 }}
          image: "{{ .Values.crudappreact.image.repository }}:{{ .Values.crudappreact.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.crudappreact.image.pullPolicy }}
          ports:
            - name: http
              containerPort: 80
              protocol: TCP
          livenessProbe:
            httpGet:
              path: /
              port: http
          readinessProbe:
            httpGet:
              path: /
              port: http
          resources:
            {{- toYaml .Values.crudappreact.resources | nindent 12 }}
      {{- with .Values.crudappreact.nodeSelector }}
      nodeSelector:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.crudappreact.affinity }}
      affinity:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      {{- with .Values.crudappreact.tolerations }}
      tolerations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
