apiVersion: v1
kind: Service
metadata:
  name: {{ include "crudappreact.fullname" . }}
  labels:
    {{- include "crudappreact.labels" . | nindent 4 }}
spec:
  type: {{ .Values.crudappreact.service.type }}
  ports:
    - port: {{ .Values.crudappreact.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "crudappreact.selectorLabels" . | nindent 4 }}
