{{- if .Values.crudappreact.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crudappreact.serviceAccountName" . }}
  labels:
    {{- include "crudappreact.labels" . | nindent 4 }}
  {{- with .Values.crudappreact.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
