apiVersion: apps/v1
kind: Deployment
metadata:
  name: crudappnode-deployment
  labels:
    app: crudappnode
spec:
  replicas: 1
  selector:
    matchLabels:
      app: crudappnode
  template:
    metadata:
      labels:
        app: crudappnode
    spec:
      containers:
      - name: crudappnode
        image: rishabhnama/crudappnode:latest
        ports:
        - containerPort: 8000
        env:
        - name: MYSQL_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysql-secret
              key: mysql-password


---
apiVersion: v1
kind: Service
metadata:
  name: crudappnode-service
spec:
  type: NodePort
  selector:
    app: crudappnode
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      nodePort: 30001

# ---
# apiVersion: apps/v1
# kind: Deployment
# metadata:
#   name: mysql-deployment
#   labels:
#     app: mysql
# spec:
#   replicas: 1
#   selector:
#     matchLabels:
#       app: mysql
#   template:
#     metadata:
#       labels:
#         app: mysql
#     spec:
#       containers:
#       - name: mysql
#         image: mysql
#         ports:
#         - containerPort: 3306
#         env:
#         # - name: root
#         #   valueFrom:
#         #     secretKeyRef:
#         #       name: mysql-secret
#         #       key: mysql-user
              
#         - name: MYSQL_ROOT_PASSWORD
#           valueFrom:
#             secretKeyRef:
#               name: mysql-secret
#               key: mysql-password

           
              

# ---
# apiVersion: v1
# kind: Service
# metadata:
#   name: mysql-service
# spec:
#   selector:
#     app: mysql
#   type: LoadBalancer
#   ports:
#     - protocol: TCP
#       port: 3306
#       targetPort: 3306
#       nodePort: 30002



