apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-node
data:
    password: {{ .Values.crudappnode.password | b64enc }}
    user: {{ .Values.crudappnode.user | b64enc }}
    password2: {{ .Values.crudappnode.password2 | b64enc }}