apiVersion: v1
kind: Service
metadata:
  name: {{ include "crudappnode.fullname" . }}
  labels:
    {{- include "crudappnode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.crudappnode.service.type }}
  ports:
    - port: {{ .Values.crudappnode.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "crudappnode.selectorLabels" . | nindent 4 }}
