{{- if .Values.crudappnode.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ include "crudappnode.serviceAccountName" . }}
  labels:
    {{- include "crudappnode.labels" . | nindent 4 }}
  {{- with .Values.crudappnode.serviceAccount.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
{{- end }}
