apiVersion: v1
kind: Service
metadata:
  name: {{ template "crudappnode.fullname" . }}
  labels:
    {{- template "crudappnode.labels" . | nindent 4 }}
spec:
  type: {{ .Values.crudappnode.service.type }}
  ports:
    - port: {{ .Values.crudappnode.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- template "crudappnode.selectorLabels" . | nindent 4 }}
