apiVersion: v1
kind: Secret
metadata:
    name: {{ .Release.Name }}-auth
data:
    password: {{ .Values.password | b64enc }}
    user: {{ .Values.user | b64enc }}
    password2: {{ .Values.password2 | b64enc }}